#!/usr/bin/env python

import os
import subprocess

filesDir = 'filesChanged'

for aDirPath, dirs, files in os.walk(filesDir) :
  if 0 < len(files) :
    print(f"\nWorking in {aDirPath}")
    if len(files) < 2 : continue
    sortedFiles = sorted(files)
    prevFile = sortedFiles.pop(0)
    prevFilePath = os.path.join(aDirPath, prevFile)
    for aFile in sortedFiles :
      print(f"  {aFile}")
      filePath = os.path.join(aDirPath, aFile)
      if not os.system(f"diff -q {prevFilePath} {filePath}") :
        os.rename(filePath, filePath+'.duplicate')
      else:
        prevFile = aFile
        prevFilePath = filePath

